### PR TITLE
Make most crops disabable

### PR DESCRIPTION
**Pull request by tacotexmex**

### CODE REVIEW

**Comment by tenplus1** [comment]
Is there any particular reason to disable certain crops ??

**Comment by tacotexmex** [comment]
For me I want a subset of your crops that matches with what I have textures for in my texture pack. I also want fewer crop types available in-game since most of them have no other use than being food, so there's the game mechanic factor as well.

**Comment by tenplus1** [comment]
Ah okies, will look into adding a settings file.

**Comment by tenplus1** [comment]
farming.conf setting file added, can be placed inside mod folder for global changes or world folder for map specific change.

**Comment by tacotexmex** [comment]
That's nice but why not global settings that's available in the central place where all other settings reside?

**Comment by tenplus1** [comment]
I'd rather not have people editing the. conf file directly, this way it's easier and safer.

**Comment by tacotexmex** [comment]
Fair enough. Thanks!

**Pull request closed without merging**
