### PR TITLE
Replace deprecated settings method

### PR DESCRIPTION
**Pull request by tacotexmex**

### CODE REVIEW

**Comment by tenplus1** [comment]
Until everyone is using 0.4.16 then we will use the old settings_get functions for compatibility.

**Comment by tacotexmex** [comment]
How do you know when that is? :)

**Comment by ExeterDad** [comment]
> Until everyone is using 0.4.16 then we will use the old settings_get functions for compatibility.
Never thought of that. I was gonna submit a patch as well. I've finally cleaned up all our installed mods as my logs were going over a gig a day with the warnings.

**Comment by tacotexmex** [comment]
Yeah, everyone on 0.4.16 need --quiet flag or log files will explode.

**Comment by tenplus1** [comment]
Sad but true, I feel the settings function didn't need to be updated but it has bringing many warnings with it.

**Pull request closed without merging**
